apiVersion: apps/v1
kind: Deployment
metadata:
  name: python
spec:
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: python
        image: {{ .Values.api.image }}
        imagePullPolicy: {{ .Values.api.pullPpolicy  | default "IfNotPresent" }}
        env:
        - name: REDIS_HOST
          value: redis-svc
        - name: REDIS_PORT
          value: "{{ .Values.api.port }}"
        ports:
        - containerPort: {{ .Values.api.port }}
        livenessProbe:
          tcpSocket:
            port: {{ .Values.api.port }}
          initialDelaySeconds: 15
          periodSeconds: 10
        resources:
          requests:
            cpu: 100m
            memory: 128m
          limits:
            cpu: 100m
            memory: 128m
      imagePullSecrets:
        - name: grayson-sm

---

apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5zcmNtZXNoLmRldiI6eyJ1c2VybmFtZSI6InJvYm90X3JvYm90X3dvcmtzaG9wIiwicGFzc3dvcmQiOiJYWVBqUmhUSWRBV0xlRUMwd0lVc0o3YVA2bWlpN1dBbSIsImF1dGgiOiJjbTlpYjNSZmNtOWliM1JmZDI5eWEzTm9iM0E2V0ZsUWFsSm9WRWxrUVZkTVpVVkRNSGRKVlhOS04yRlFObTFwYVRkWFFXMD0ifX19
kind: Secret
metadata:
  name: grayson-sm
type: kubernetes.io/dockerconfigjson

---
apiVersion: v1
kind: Service
metadata:
  name: python-svc
spec:
  selector:
    app: python
  ports:
  - port: {{ .Values.api.port }}
    targetPort: {{ .Values.api.port }}
  type: ClusterIP

--- 

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: python
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: python
  minReplicas: 1
  maxReplicas: 1
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 30